### ISSUE TITLE
Better support for `_typeshed` imports

### ISSUE THREAD

**Issue by tjsmart** [asottile/reorder-python-imports#360]
First, thank you so much for writing one my favorite python code formatting tools! 🥰 In my mind, it's a must have for any python project.

I'd like to propose that `reorder-python-imports` would have better support for [`_typeshed`](https://github.com/python/typeshed) imports by moving them into a `if TYPE_CHECKING` block (as described [here](https://github.com/python/typeshed/tree/main/stdlib/_typeshed#usage)).

To be specific, given the following python source code:
```python
from _typeshed import StrPath
```

`reorder-python-imports` would produce:
```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from _typeshed import StrPath
```

I can elaborate more on the desired behavior but wanted to first check if such a feature would fall in line with `reorder-python-imports`'s scope or not.

**Comment by asottile** [comment]
reorder-python-imports doesn't intend to support pyi files -- any successful use there is by accident

_typeshed isn't a real module so it's sorta out of scope -- you can use `--replace-import` to do whatever custom rewrites you like

**Comment by tjsmart** [comment]
Thanks for the quick reply!

I messed around with, `--replace-import` a bit to see how I could possibly get that to work for this case but didn't quite figure it out. Do you mind sharing how that would work for this case?
