### ISSUE TITLE
Allow grouping of from imports

### ISSUE THREAD

**Issue by jgbradley1** [asottile/reorder-python-imports#365]
[PEP-328](https://peps.python.org/pep-0328) talks about allowing multi-line import statements and grouping imports inside parentheses such as 
```
from math import acos, atan,floor, \
    pi
```

Currently this project converts the statement above to
```
from math import acos
from math import atan
from math import floor
from math import pi
```

However a valid and cleaner transformation that follows the spirit of this project (to reduce the number of merge conflicts) should allow for users to have the following format:
```
from math import (
    acos,
    atan,
    floor,
    pi
)
```
For functions that exist in a deeply nested module (`from some.very.long.module.path.that.looks.ugly import ...`) , a single from import statement with parentheses is less verbose and cleaner to read/understand.

**Comment by asottile** [comment]
search for dupes next time
