### ISSUE TITLE
Clash with black formatter (new line after module docstring)

### ISSUE THREAD

**Issue by elagil** [asottile/reorder-python-imports#366]
`reorder-python-imports` worked together fine with `black` up to version 23. From version 24, black seems to have introduced a forced new line after the module docstring.

`reorder-python-imports` apparently forces **no** new line after the module docstring.

How can I use the two together as pre-commit hooks without conflict? Neither seems to be configurable in this regard.

Thanks in advance

**Comment by asottile** [comment]
open an issue with black then

**Comment by maxwell-k** [comment]
First: I'm a huge fan of reorder-python imports, thank you! Second I followed your suggestion and opened <https://github.com/psf/black/issues/4175>. Please allow me to ask:

Do you think its possible that any future version of `reorder-python-imports` might allow or preserve a blank line between a module level doc-string at the top of a file and the first import?

The behaviour I'm asking about is:

```
"""Module docstring."""

import typing
```

In place of:

```
"""Module docstring."""
import typing
```
