### ISSUE TITLE
Black `24.1.1` Conflict

### ISSUE THREAD

**Issue by cooncesean** [asottile/reorder-python-imports#367]
# Issue Description 
Our team just upgraded major versions from `black==23.1.0` to `black==24.1.1` (https://github.com/psf/black/releases/tag/24.1.1) which was just released two days ago. This introduces a conflict with `reorder-python-imports` (which we also use) around the introduction of new blank lines after a module-level docstring. `black` wants to introduce a new line between the docstring and the first line of code. `reorder-python-imports` wants that line to be removed. 

It appears that that is the lone issue. [Video of this in action](https://www.loom.com/share/1b1f1922480f4e0ea00ae3fd7a5adcae).

# Steps To Reproduce

1. Upgrade your local version of `black` to their most recent release. 
2. Modify a file with a module level docstring. 
3. Run the `black` command locally.
4. Run the `reorder-python-imports` command locally. 
5. See the conflict.

Thanks for the assist and this fantastic tool; LMK if there is anything else I can do to help.

**Comment by asottile** [comment]
search the issue tracker next time
