### ISSUE TITLE
Removes new line for files

### ISSUE THREAD

**Issue by NazarioJL** [asottile/reorder-python-imports#388]
## Description

`reorder-python-imports` will remove lines in between top level file comments and the first import. The issue is that `reorder-python-imports` takes a stance on file formatting _beyond_ the import section.

Input file:

```python
"""This is a comment"""

import os
from datetime import datetime

print(os.name)
print(datetime.now())

```

Output file:
```python
"""This is a comment"""
import os
from datetime import datetime

print(os.name)
print(datetime.now())

```

Commonly used formatters like `black` and `ruff` disagree with this.

**Comment by asottile** [comment]
there are many duplicates

this tool has been consistently formatting everything until the end of the imports since 2015 -- years before the other tools existed

I don't use the other tools and don't really care if you use my tool.  I'm not changing it because black made a rash decision
