### ISSUE TITLE
Compatibility issue with pyupgrade

### ISSUE THREAD

**Issue by PhilippWillms** [asottile/reorder-python-imports#398]
I see a lot of benefits in `pyuprgade `and wanted to introduce it to my repository, where I host an application for Python 3.8+.

However, there is incompatibility issue when using `black `formatter and, in particular, the `reorder-python-imports` plugin.

**Observation:**
1. `reorder-python-imports` does not consider the empty line below module docstring, which is foreseen with PEP 257.
2. `black `formatting puts the empty line in.

Structuring the pre-commit-config.yml becomes a challenge. Current approach is to put reorder-python-imports hook first, then pyupgrade, and then finally black formatting. However, due to the "back-and-forth" formatting, pre-commit shows "error" and will not let the commit pass through.

**Comment by asottile** [comment]
this tool is compatible with pyupgrade and / or you are not good at searching the issue tracker
